#!/bin/sh

# See LICENSE file for copyright and license details.

# Check if I2Pd is installed and running on different systems
if command -v dpkg > /dev/null; then
	if dpkg -l | grep -q i2pd; then
		check_i2pd_running
	else
		echo "I2Pd is not installed. Please install I2Pd to proceed using the browser."
		echo "https://i2pd.readthedocs.io/en/latest/user-guide/install/#linux"
	fi
elif command -v pacman > /dev/null; then
	if pacman -Qs i2pd > /dev/null; then
		check_i2pd_running
	else
		echo "I2Pd is not installed. Please install I2Pd to proceed using the browser."
		echo "https://i2pd.readthedocs.io/en/latest/user-guide/install/#linux"
	fi
elif command -v emerge > /dev/null; then
	if emerge --search i2pd | grep -q "Latest version available"; then
		check_i2pd_running
	else
		echo "I2Pd is not installed. Please install I2Pd to proceed using the browser."
		echo "https://i2pd.readthedocs.io/en/latest/user-guide/install/#linux"
	fi
elif command -v xbps-query > /dev/null; then
	if xbps-query -Rs i2pd > /dev/null; then
		check_i2pd_running
	else
		echo "I2Pd is not installed. Please install I2Pd to proceed using the browser."
		echo "https://i2pd.readthedocs.io/en/latest/user-guide/install/#linux"
	fi
else
	echo "Unsupported package manager. Please ensure I2Pd is installed and running."
	echo "https://i2pd.readthedocs.io/en/latest/user-guide/install/#linux"
	exit 1
fi

arch=$(uname -m)

screenfind=$(which screen)
if [ -z $screenfind ]; then
	echo "Can't find 'screen' installed. This script needs it!";
	exit 1;
fi

if [ $arch = "x86_64" ]; then
	screen -Adm -S i2pd /usr/sbin/i2pd --datadir=.
else
	echo "Your system architecture is not supported."
	exit 1
fi
